# Generated by Django 5.1.3 on 2024-11-15 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'permissions': [('can_view_position', 'Can view position'), ('can_add_position', 'Can add position'), ('can_edit_position', 'Can edit position'), ('can_delete_position', 'Can delete position')]},
        ),
    ]
