# Generated by Django 5.1.3 on 2024-11-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_position_options'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={},
        ),
        migrations.RemoveField(
            model_name='position',
            name='rights',
        ),
        migrations.AddField(
            model_name='position',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission'),
        ),
    ]
