# Generated by Django 5.1.3 on 2024-11-15 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_position_options_remove_position_rights_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='positions',
        ),
        migrations.AddField(
            model_name='employee',
            name='available_positions',
            field=models.ManyToManyField(blank=True, related_name='available_employees', to='api.position'),
        ),
        migrations.AddField(
            model_name='employee',
            name='current_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_employees', to='api.position'),
        ),
    ]
