# Generated by Django 5.1.3 on 2024-11-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_employee_positions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='position',
            name='permissions',
        ),
        migrations.AddField(
            model_name='position',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='positions', to='api.department'),
        ),
    ]
