# Generated by Django 5.1.3 on 2024-11-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_department_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='departments',
        ),
        migrations.AddField(
            model_name='department',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='departments', to='api.position'),
        ),
    ]
