# Generated by Django 5.1.3 on 2024-11-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_position_departments_department_positions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('codename', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='positions', to='api.permission'),
        ),
    ]
